# Generated by Django 5.1 on 2024-11-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_bloggerprofilemodel_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='Profile_Pic',
            field=models.ImageField(null=True, upload_to='Media/Profile_Pic'),
        ),
    ]
