# Generated by Django 5.1 on 2024-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_custom_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloggerprofilemodel',
            name='Profile_Pic',
        ),
        migrations.RemoveField(
            model_name='viewersprofilemodel',
            name='Profile_Pic',
        ),
        migrations.AddField(
            model_name='bloggerprofilemodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloggerprofilemodel',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='interest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='preferred_content_type',
            field=models.CharField(blank=True, choices=[('articles', 'Articles'), ('videos', 'Videos'), ('both', 'Both')], max_length=100, null=True),
        ),
    ]
